version: '3.3'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: cem-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    networks:
      - cem-network

  auth-db:
    image: postgres:11
    container_name: cem-authdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_AUTH_PORT}:5432'
    volumes:
      - /var/lib/postgresql/authdb/data:/var/lib/postgresql/data
    networks:
      - cem-network
  
  product-db:
    image: postgres:11
    container_name: cem-productdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PRODUCT_PORT}:5432'
    volumes:
      - /var/lib/postgresql/productdb/data:/var/lib/postgresql/data
    networks:
      - cem-network
      
networks:
  cem-network:
    driver: bridge
