version: '3.3'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: cem-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    networks:
      - cem-network

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    image: auth-api
    container_name: cem-auth-api
    restart: unless-stopped
    ports:
      - '${AUTH_API_PORT}:80'
    networks:
      - cem-network

  auth-db:
    image: postgres:11
    container_name: cem-authdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_AUTH_PORT}:5432'
    volumes:
      - /var/lib/postgresql/authdb/data:/var/lib/postgresql/data
    networks:
      - cem-network

  product-api:
    build:
      context: ./product-api
      dockerfile: Dockerfile
    image: product-api
    container_name: cem-product-api
    restart: unless-stopped
    ports:
      - '${PRODUCT_API_PORT}:80'
    networks:
      - cem-network
  
  product-db:
    image: postgres:11
    container_name: cem-productdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PRODUCT_PORT}:5432'
    volumes:
      - /var/lib/postgresql/productdb/data:/var/lib/postgresql/data
    networks:
      - cem-network

  sales-api:
    build:
      context: ./sales-api
      dockerfile: Dockerfile
    image: sales-api
    container_name: cem-sales-api
    restart: unless-stopped
    ports:
     - '${SALES_API_PORT}:80'
    networks:
      - cem-network

  sales-db:
    image: tutum/mongodb
    container_name: cem-sales-db
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: sales
      MONGODB_USER: ${DB_USERNAME}
      MONGODB_PASS: ${DB_PASSWORD}
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - /var/lib/mongodb/sales/data:/data/db
    networks:
      - cem-network

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: cem-sales-rabbit
    hostname: cem-sales-rabbit
    ports:
      - '5672:5672'
      - '25676:25676'
      - '15672:15672'
    networks:
      - cem-network

networks:
  cem-network:
    driver: bridge
